### ISSUE TITLE
ToDo: fix mimo_matching_v4 for python 3.9

### ISSUE THREAD

**Issue by boeddeker** [fgnt/meeteval#31]
```
Python 3.9.17 (main, Jul 28 2023, 05:54:52) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.14.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from meeteval.wer.matching import orc_matching, mimo_matching
   ...: ref=[['a']]
   ...: hyps=['aaabb']
   ...: mimo_matching.mimo_matching_v4(ref, hyps)
   ...: 
Out[1]: (2, [(0, 0)])
```

```
Python 3.11.4 (main, Jul  5 2023, 13:45:01) [GCC 11.2.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.14.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from meeteval.wer.matching import orc_mat
ching, mimo_matching
   ...: ref=[['a']]
   ...: hyps=['aaabb']
   ...: mimo_matching.mimo_matching_v4(ref, hyps)
   ...: 
Out[1]: (4, [(0, 0)])
```

See GitHub Action log: [logs_144.zip](https://github.com/fgnt/meeteval/files/12227541/logs_144.zip)

**Comment by boeddeker** [comment]
I was able to reproduce this error in a fresh environment, but I was not able to reproduce this error in an old environment.

**Comment by thequilo** [comment]
I was not able to reproduce this issue in a local fresh Python 3.9 environment. Can you reproduce it reliably? It also seems to appear randomly in the GitHub actions builds.

**Comment by boeddeker** [comment]
Note:
In production, this bug will trigger an AssertionError and not a silent error (i.e. wrong WER).
In MIMO-WER and ORC-WER we apply the assignment and check the lev distance with kaldialign.
