### ISSUE TITLE
CTM files with comments can't be parsed 

### ISSUE THREAD

**Issue by D-VR** [fgnt/meeteval#4]
If you try to use CTM files with comments in them (as defined in https://github.com/usnistgov/SCTK/blob/f48376a203ab17f0d479995d87275db6772dcb4a/doc/infmts.htm#L285 ) meeteval throws a error.

Reason: When reading lines from CTM files, meeteval ignores empty lines, but lines with comments (starting with ";;") also need to be ignored.

**Comment by boeddeker** [comment]
Thanks for reporting the missing support for comments. I will add it.
